#!/usr/bin/env python3
"""Build deterministic content indexes for docs, paper sections, and research."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import NamedTuple


if __package__:
    from .reproducible_time import generated_at_utc
else:
    from reproducible_time import generated_at_utc


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_INDEX_TOML = REPO_ROOT / "data" / "registry" / "docs_index.toml"
DOCS_INDEX_MD = REPO_ROOT / "docs" / "DOCS_INDEX.md"


class IndexScope(NamedTuple):
    root: Path
    extensions: set[str]
    excluded_prefixes: set[str]
    excluded_files: set[str]


INDEX_SCOPES = (
    IndexScope(
        root=REPO_ROOT / "docs",
        extensions={".md", ".txt"},
        excluded_prefixes={"docs/sphinx/"},
        excluded_files={"docs/DOCS_INDEX.md"},
    ),
    IndexScope(
        root=REPO_ROOT / "papers" / "sections",
        extensions={".tex"},
        excluded_prefixes=set(),
        excluded_files=set(),
    ),
    IndexScope(
        root=REPO_ROOT / "research",
        extensions={".txt", ".md", ".tex", ".json", ".toml", ".yml", ".yaml"},
        excluded_prefixes=set(),
        excluded_files=set(),
    ),
)


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def category_for(relpath: str) -> str:
    if relpath.startswith("docs/external_sources/"):
        return "docs/external_sources"
    if relpath.startswith("docs/"):
        return "docs/root"
    if relpath.startswith("papers/sections/"):
        return "papers/sections"
    if relpath.startswith("research/"):
        parts = relpath.split("/")
        if len(parts) >= 3:
            return f"research/{parts[1]}"
        return "research/root"
    return "misc"


def title_for(relpath: str, text: str) -> str:
    def is_decorative_line(value: str) -> bool:
        if not value:
            return True
        stripped = value.strip()
        if not stripped:
            return True
        return (
            len(stripped) >= 5
            and len(set(stripped)) == 1
            and stripped[0] in {"=", "-", "_", "*", "~"}
        )

    if relpath.endswith(".md"):
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                return stripped.lstrip("#").strip()[:180]
    if relpath.endswith(".tex"):
        tex_heading = re.search(r"\\(?:chapter|section|subsection)\*?\{([^}]+)\}", text)
        if tex_heading:
            return tex_heading.group(1).strip()[:180]
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not is_decorative_line(stripped):
            return stripped[:180]
    return "(untitled)"


def should_include(relpath: str, scope: IndexScope) -> bool:
    if relpath in scope.excluded_files:
        return False
    for prefix in scope.excluded_prefixes:
        if relpath.startswith(prefix):
            return False
    suffix = Path(relpath).suffix.lower()
    return suffix in scope.extensions


def docs_id_from_relpath(relpath: str) -> str:
    base = relpath
    for prefix in ("docs/", "papers/sections/", "research/"):
        if base.startswith(prefix):
            base = base.removeprefix(prefix)
            break
    slug = base.replace("/", "__").replace(" ", "_").replace(".", "_")
    lane = relpath.split("/", 1)[0]
    return f"{lane}_{slug.lower()}"


def to_toml(rows: list[dict[str, str | int]], generated_at_utc: str) -> str:
    lines: list[str] = []
    lines.append('generated_by = "scripts/build_docs_index.py"')
    lines.append(f'generated_at_utc = "{generated_at_utc}"')
    lines.append(f"documents_total = {len(rows)}")
    lines.append("")
    for row in rows:
        lines.append("[[documents]]")
        lines.append(f'id = "{row["id"]}"')
        lines.append(f'relpath = "{row["relpath"]}"')
        lines.append(f'category = "{row["category"]}"')
        escaped_title = str(row["title"]).replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'title = "{escaped_title}"')
        lines.append(f'sha256 = "{row["sha256"]}"')
        lines.append(f"line_count = {row['line_count']}")
        lines.append(f"size_bytes = {row['size_bytes']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def to_markdown(rows: list[dict[str, str | int]], generated_at_utc: str) -> str:
    categories: dict[str, list[dict[str, str | int]]] = {}
    for row in rows:
        categories.setdefault(str(row["category"]), []).append(row)

    lines: list[str] = []
    lines.append("# Documentation Index")
    lines.append("")
    lines.append("This file is generated by `scripts/build_docs_index.py`.")
    lines.append("")
    lines.append(f"Generated at: `{generated_at_utc}`")
    lines.append(f"Total documents indexed: `{len(rows)}`")
    lines.append("")

    for category in sorted(categories):
        lines.append(f"## {category}")
        lines.append("")
        for row in sorted(categories[category], key=lambda item: str(item["relpath"])):
            lines.append(
                f"- `{row['relpath']}`: {row['title']} "
                f"(lines: {row['line_count']}, bytes: {row['size_bytes']})"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    DOCS_INDEX_TOML.parent.mkdir(parents=True, exist_ok=True)
    DOCS_INDEX_MD.parent.mkdir(parents=True, exist_ok=True)
    generated_timestamp = generated_at_utc()

    rows: list[dict[str, str | int]] = []
    seen_relpaths: set[str] = set()
    for scope in INDEX_SCOPES:
        if not scope.root.exists():
            continue
        for path in sorted(scope.root.rglob("*")):
            if not path.is_file():
                continue
            relpath = path.relative_to(REPO_ROOT).as_posix()
            if relpath in seen_relpaths:
                continue
            if not should_include(relpath, scope):
                continue
            seen_relpaths.add(relpath)

            text = path.read_text(encoding="utf-8", errors="replace")
            line_count = text.count("\n") + (0 if text == "" else 1)
            row = {
                "id": docs_id_from_relpath(relpath),
                "relpath": relpath,
                "category": category_for(relpath),
                "title": title_for(relpath, text),
                "sha256": sha256_text(text),
                "line_count": line_count,
                "size_bytes": len(text.encode("utf-8")),
            }
            rows.append(row)

    DOCS_INDEX_TOML.write_text(to_toml(rows, generated_timestamp), encoding="utf-8")
    DOCS_INDEX_MD.write_text(to_markdown(rows, generated_timestamp), encoding="utf-8")

    print(f"Wrote docs registry: {DOCS_INDEX_TOML.relative_to(REPO_ROOT).as_posix()}")
    print(f"Wrote docs index: {DOCS_INDEX_MD.relative_to(REPO_ROOT).as_posix()}")
    print(f"Indexed docs files: {len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
