#!/usr/bin/env python3
"""Generate the paper's critique table from the canonical evidence ledger."""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
LEDGER_PATH = REPO_ROOT / "data" / "registry" / "critique_evidence_ledger.json"
OUTPUT_PATH = REPO_ROOT / "papers" / "generated" / "critique_reassessment_rows.tex"

LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(value: str) -> str:
    return "".join(LATEX_ESCAPES.get(character, character) for character in value)


def load_claims(ledger_path: Path = LEDGER_PATH) -> list[dict[str, object]]:
    payload = json.loads(ledger_path.read_text(encoding="utf-8"))
    claims = payload.get("claims")
    if not isinstance(claims, list) or not claims:
        raise ValueError("critique evidence ledger must contain a non-empty claims list")

    seen_ids: set[str] = set()
    for claim in claims:
        if not isinstance(claim, dict):
            raise TypeError("every critique evidence entry must be an object")
        claim_id = str(claim.get("id", "")).strip()
        if not claim_id:
            raise ValueError("every critique evidence entry must define an id")
        if claim_id in seen_ids:
            raise ValueError(f"duplicate critique evidence id: {claim_id}")
        seen_ids.add(claim_id)

        evidence_paths = claim.get("evidence_paths")
        if not isinstance(evidence_paths, list) or not evidence_paths:
            raise ValueError(f"critique {claim_id} must define evidence_paths")
        for evidence_relpath in evidence_paths:
            evidence_path = REPO_ROOT / str(evidence_relpath)
            if not evidence_path.exists():
                raise FileNotFoundError(
                    f"critique {claim_id} references missing evidence: {evidence_relpath}"
                )

    return claims


def render_rows(claims: list[dict[str, object]]) -> str:
    lines = ["% Generated by scripts/generate_critique_evidence_table.py."]
    for claim in claims:
        critique = latex_escape(str(claim["critique"]))
        attempt = latex_escape(str(claim["falsification_attempt"]))
        status = latex_escape(str(claim["status"]).capitalize())
        verdict = latex_escape(str(claim["verdict"]))
        lines.extend(
            [
                f"  {critique} &",
                f"    {attempt} &",
                f"    {status}: {verdict} \\\\",
            ]
        )
    lines.append(r"  \bottomrule")
    return "\n".join(lines) + "\n"


def main() -> int:
    claims = load_claims()
    output = render_rows(claims)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(claims)} critique rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
