#!/usr/bin/env python3
"""Render the bridge's reading routes from the validated library contract."""

from __future__ import annotations

import argparse
import json

from validate_learning_library import ROOT, validate_library


def escape(text: str) -> str:
    return text.replace("&", r"\&").replace("_", r"\_").replace("%", r"\%")


def render() -> str:
    library = json.loads((ROOT / "docs/learning/library.json").read_text())
    errors = validate_library(library)
    if errors:
        raise ValueError("; ".join(errors))
    nodes = {node["id"]: node for node in library["nodes"]}
    paragraphs = ["% Generated by scripts/render_learning_routes.py from library.json."]
    for route in library["routes"]:
        steps = []
        for identifier in route["nodes"]:
            node = nodes[identifier]
            if node["book"] == "precalculus":
                steps.append("Precalculus")
            elif node["book"] == "bridge":
                name = escape(identifier.replace("_", " "))
                steps.append(
                    r"\hyperref[learn:"
                    + identifier
                    + "]{"
                    + name
                    + r" (\ref*{learn:"
                    + identifier
                    + "})}"
                )
            else:
                steps.append("Review: " + escape(node["title"]))
        paragraphs.append(r"\textbf{" + escape(route["title"]) + ".} " + "; ".join(steps) + ".")
    return "\n\n".join(paragraphs) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    target = ROOT / "papers/learning/generated_routes.tex"
    content = render()
    if arguments.check:
        if not target.is_file() or target.read_text() != content:
            print("Reading routes need regeneration: python3 scripts/render_learning_routes.py")
            return 1
    else:
        target.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
