#!/usr/bin/env python3
"""Generate reader routes, lesson cards, and solution locators from one curriculum."""

from __future__ import annotations

import argparse
import json
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from pathlib import Path

from validate_learning_library import ROOT, validate_library


def escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "_": r"\_",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "{": r"\{",
        "}": r"\}",
        "^": r"\textasciicircum{}",
        "~": r"\textasciitilde{}",
        "<": r"\textless{}",
        ">": r"\textgreater{}",
    }
    return "".join(replacements.get(character, character) for character in text)


def tex_link(node: dict) -> str:
    title = escape(node["title"])
    if node["book"] == "bridge":
        return r"\hyperref[learn:" + node["id"] + "]{" + title + "}"
    return (
        r"\href{https://github.com/Oichkatzelesfrettschen/"
        + (
            "precalc_paper"
            if node["book"] == "precalculus"
            else "MathScienceCompendium/blob/main/docs/learning/lessons/" + node["id"] + ".md"
        )
        + "}{"
        + ("Companion: " if node["book"] == "precalculus" else "Review guide: ")
        + title
        + "}"
    )


def md_link(node: dict, prefix: str = "") -> str:
    return f"[{node['title']}]({prefix}{node['id']}.md)"


def render_outputs(library: dict) -> dict[Path, str]:
    errors = validate_library(library)
    if errors:
        raise ValueError("; ".join(errors))
    nodes = {node["id"]: node for node in library["nodes"]}
    books = {book["id"]: book for book in library["books"]}
    outputs = {}
    routes_tex = ["% Generated by scripts/render_learning_routes.py from library.json."]
    solutions = [
        r"\chapter{Readiness solutions}",
        r"\label{learn:solutions}",
        "Compare the operations as well as the final value. Return to the named lesson when a step needs repair.",
    ]
    for route in library["routes"]:
        routes_tex += [
            r"\section*{" + escape(route["question"]) + "}",
            escape(route["starting_knowledge"]),
            "; ".join(tex_link(nodes[key]) for key in route["nodes"]) + ".",
        ]
        lines = [
            f"# {route['question']}",
            "",
            f"**Purpose:** {route['purpose']}",
            "",
            route["starting_knowledge"],
            "",
            "[Start here](../README.md) | [Look up a method](../METHOD_FINDER.md) | [Evidence guide](../EVIDENCE_GUIDE.md)",
            "",
            "Read in the order below. A passed entry check lets you use prior knowledge; use the repair link when a step is unfamiliar. Helpful background adds context and stays separate from required lessons.",
            "",
        ]
        for index, key in enumerate(route["nodes"], 1):
            node = nodes[key]
            lines += [
                f"## {index}. {node['title']}",
                "",
                node["question"],
                "",
                "**Learn to:** " + " ".join(node["outcomes"]),
                "",
                "**Required lessons:** "
                + (
                    ", ".join(md_link(nodes[req], "../lessons/") for req in node["requires"])
                    or "Start with this orientation."
                ),
                "",
                "**Helpful background:** " + " ".join(node["helpful"]),
                "",
                "**Ready to continue when:** " + node["readiness"]["prompt"],
                "",
                md_link(node, "../lessons/")
                + " supplies the entry check, solution, source, and next-step reasons.",
                "",
            ]
        outputs[ROOT / f"docs/learning/routes/{route['id']}.md"] = "\n".join(lines)
    outputs[ROOT / "papers/learning/generated_routes.tex"] = "\n\n".join(routes_tex) + "\n"
    finder = [
        "# Look up a method",
        "",
        "[Start here](README.md) | [Examine a claim](EVIDENCE_GUIDE.md)",
        "",
        "Choose the operation you need. Each lesson page separates required knowledge, helpful background, practice, and the next useful question.",
        "",
        "| Question | Lesson and role |",
        "|---|---|",
    ]
    for node in library["nodes"]:
        key = node["id"]
        book = books[node["book"]]
        finder.append(f"| {node['question']} | {md_link(node, 'lessons/')} ({node['role']}) |")
        source_url = (
            (book["repository"] + "/blob/main/" + node["source"])
            if book.get("repository")
            else "../../../" + node["source"]
        )
        lines = [
            f"# {node['title']}",
            "",
            "[Start here](../README.md) | [Method finder](../METHOD_FINDER.md) | [Evidence guide](../EVIDENCE_GUIDE.md)",
            "",
            f"**You are here:** {book['title']} / {node['role']}",
            "",
            f"**Question:** {node['question']}",
            "",
            f"[Read the source]({source_url}). In the separate PDF, open **{node['pdf_title'] or 'Begin with a Problem'}** in **{book['title']}**. The built album directory supplies the verified physical page and PDF link.",
            "",
            "## Bring forward",
            "",
            ", ".join(md_link(nodes[req]) for req in node["requires"])
            or "Begin with this orientation; repair links introduce any unfamiliar operation.",
            "",
            "**Helpful background:** " + " ".join(node["helpful"]),
            "",
            "## What you will learn",
            "",
        ] + [f"- {outcome}" for outcome in node["outcomes"]]
        lines += [
            "",
            "## Entry check",
            "",
            node["entry_check"]["prompt"],
            "",
            "<details><summary>Check your entry answer</summary>",
            "",
            node["entry_check"]["answer"],
            "",
            "</details>",
            "",
            "**If a step is unfamiliar:** " + md_link(nodes[node["entry_check"]["repair"]]) + ".",
            "",
            "## Practice and readiness",
            "",
            node["readiness"]["prompt"],
            "",
            "<details><summary>Read the worked readiness solution</summary>",
            "",
            node["readiness"]["answer"],
            "",
            "</details>",
            "",
            "Continue when you can explain the operations and assumptions as well as the value. Otherwise revisit the lesson method and try its solved practice.",
            "",
            "## Quick reference",
            "",
            "**Use:** " + node["reference"]["use"],
            "",
            "**Watch:** " + node["reference"]["watch"],
            "",
            "## Next useful question",
            "",
        ]
        lines += [
            f"- {md_link(nodes[step['node']])}: {step['why']} Check that lesson's remaining prerequisites before continuing."
            for step in node["next"]
        ]
        lines += [
            "",
            "**Evidence and computation:** [Classify the claim and locate its supporting record](../EVIDENCE_GUIDE.md).",
            "",
        ]
        if node["entry_check"]["repair"] == "precalc":
            lines += [
                "",
                "For the failed foundational operation, open the independent companion method finder: [Precalculus Through Problems of the Past](https://github.com/Oichkatzelesfrettschen/precalc_paper). Use **Equations and Balance** for elimination, **Completing and Solving a Square** for expansion, **Sequences and Sums** for geometric tails, or **Quantities and Shares** for fractions.",
                "",
            ]
        outputs[ROOT / f"docs/learning/lessons/{key}.md"] = "\n".join(lines)
        if node["book"] != "bridge":
            continue
        entry = [
            r"\begin{learningcard}{Bring forward and choose your next operation}",
            r"\textsf{\textbf{Question.}} " + escape(node["question"]) + r"\par",
            r"\textbf{Required lessons.} "
            + (", ".join(tex_link(nodes[req]) for req in node["requires"]) or "Begin here.")
            + r"\par",
            r"\textbf{Helpful background.} " + escape(" ".join(node["helpful"])) + r"\par",
            r"\textbf{Learn to.} " + escape(" ".join(node["outcomes"])) + r"\par",
            r"\textbf{Entry check.} " + escape(node["entry_check"]["prompt"]) + r"\par",
            r"\hyperref[solution:entry:"
            + key
            + r"]{Check your answer}; repair the operation in "
            + tex_link(nodes[node["entry_check"]["repair"]])
            + ".",
            r"\end{learningcard}",
        ]
        readiness = [
            r"\section*{Ready for the next question?}",
            r"\label{readiness:" + key + "}",
            escape(node["readiness"]["prompt"]),
            r"\par\hyperref[solution:ready:"
            + key
            + r"]{Read the worked readiness solution.} Continue when you can explain the operations and assumptions. Otherwise return to the method and its solved exercises.",
            r"\lessonreference{"
            + escape(node["reference"]["use"])
            + "}{"
            + escape(node["reference"]["watch"])
            + "}{"
            + r"\par ".join(
                tex_link(nodes[step["node"]]) + ": " + escape(step["why"]) for step in node["next"]
            )
            + "}",
        ]
        if key in ("matrix_maps", "complex_numbers"):
            readiness = readiness[:-1]
        outputs[ROOT / f"papers/learning/generated/{key}_entry.tex"] = "\n".join(entry) + "\n"
        outputs[ROOT / f"papers/learning/generated/{key}_ready.tex"] = "\n".join(readiness) + "\n"
        solutions += [
            r"\section{Solutions: " + escape(node["title"]) + "}",
            r"\label{solution:entry:" + key + "}",
            r"\textbf{Entry answer.} " + escape(node["entry_check"]["answer"]) + r"\par",
            r"\label{solution:ready:" + key + "}",
            r"\textbf{Readiness answer.} " + escape(node["readiness"]["answer"]) + r"\par",
            r"\hyperref[learn:"
            + key
            + r"]{Return to the lesson} or \hyperref[readiness:"
            + key
            + r"]{return to its next-question check}.",
        ]
    outputs[ROOT / "docs/learning/METHOD_FINDER.md"] = "\n".join(finder) + "\n"
    outputs[ROOT / "papers/learning/generated_solutions.tex"] = "\n\n".join(solutions) + "\n"
    return outputs


def render() -> str:
    library = json.loads((ROOT / "docs/learning/library.json").read_text())
    return render_outputs(library)[ROOT / "papers/learning/generated_routes.tex"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    library = json.loads((ROOT / "docs/learning/library.json").read_text())
    stale = []
    for target, content in render_outputs(library).items():
        if arguments.check:
            if not target.is_file() or target.read_text() != content:
                stale.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    if stale:
        print("Regenerate with python3 scripts/render_learning_routes.py: " + ", ".join(stale))
    return int(bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
