from scripts.generate_critique_evidence_table import latex_escape, load_claims, render_rows


def test_critique_evidence_ledger_has_unique_resolved_entries() -> None:
    claims = load_claims()

    assert len(claims) == 21
    assert len({claim["id"] for claim in claims}) == len(claims)


def test_render_rows_emits_one_latex_row_per_claim() -> None:
    claims = load_claims()
    rendered = render_rows(claims)

    assert rendered.count("\\\\\n") == len(claims)
    assert "Generated by scripts/generate_critique_evidence_table.py" in rendered


def test_latex_escape_protects_special_characters() -> None:
    assert latex_escape("P/Q & rho_0") == r"P/Q \& rho\_0"
